name: flutter_unit_test_sample
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  mockito: ^5.4.5
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
